### PR TITLE
Fix mailto support for CAA 'iodef' (ref: #73)

### PR DESCRIPTION
**Pull request by LarsArtmann**
#73

### CODE REVIEW

**Comment by LarsArtmann** [comment]
@vetal2409 commits are signed off, DCO passes

**Comment by LarsArtmann** [comment]
Can somebody merge this?

**Comment by kurok** [comment]
I will pass it to right person - thank for contribute

**Comment by vetal2409** [comment]
@LarsArtmann, Thank you for your contribution. I am very sorry for the late reply. We will work on proper notification.

Changing "vendor" folder isn't a good idea because it is auto-generated and all the manual changes will be lost.
I made this fix in [go-namecheap-sdk](https://github.com/namecheap/go-namecheap-sdk) and updated this terrafrom provider with this new SDK.

[Terraform Provider v2.2.0](https://registry.terraform.io/providers/namecheap/namecheap/latest/docs) should work as you expected.  Just let us know if you have any issues with it.

**Pull request closed without merging**
